### ISSUE TITLE
[Bug report] rspack config error

### ISSUE THREAD

**Issue by maquannene** [unplugin/unplugin-vue-markdown#44] opened 2024-03-14 01:56 UTC
### Describe the bug

Code ljke this：
![image](https://github.com/unplugin/unplugin-vue-markdown/assets/8757564/62960127-30bd-488f-be92-e3d7a5d256df)

But has a error when dev：
![image](https://github.com/unplugin/unplugin-vue-markdown/assets/8757564/256a2e08-41eb-48ff-a8f6-474a0cfa848a)

Could you mind give me a example to show how to config when use rspack。

### Reproduction

~

### System Info

```Shell
"@rspack/cli": "0.5.7"
"@rspack/core": "0.5.7"

yarn 1.22.19
node v16.14.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-03-14 09:21
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-14 09:21 UTC
