### ISSUE TITLE
Any Render fails when upgrade from 0.25.2 to 0.26.0

### ISSUE THREAD

**Issue by vazir** [unplugin/unplugin-vue-markdown#41] opened 2024-03-03 20:11 UTC
### Describe the bug

Any Render fails when upgrading from 0.25.2 to 0.26.0

11:07:24 PM [vite] Internal server error: Element is missing end tag.
  Plugin: vite:vue
  File: src/markdown/index.md

> Some markdown <RouterLink :to ...
at createCompilerError ([....]/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1329:17)

### Reproduction

Just change 0.25.2 to 0.26.0 and npm install

### System Info

```Shell
quasar
 » Dev mode............... spa
 » Pkg quasar............. v2.14.6
 » Pkg @quasar/app-vite... v1.7.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-03-03 20:25
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-03 20:25 UTC

**Comment by vazir** [comment] 2024-03-04 09:06
Hi @antfu , sorry, yes - here is the repo I quickly made to reproduce the behavior. By default it contains 0.26.0 which does not work. If you change version to 0.25.2 in package.json and do 'npm install' - it works fine.

https://github.com/vazir/quasar-md-test-unplugin
